Navigation buttons
slosa-smartare/frontend pull request #42
Opened 2020-10-23 18:58 UTC by PriscilaAlfaro

2020-10-24 22:59 UTC, kosmolet requested changes

2020-10-24 22:59 UTC, kosmolet commented on src/App.js
> +            <ThankYouPage path="thank-you" />
In Thanks component we should display CreatorName. Could you fix it? The creator's name is not shown anymore. It's looks like related test is also failing.

2020-10-26 10:24 UTC, kosmolet submitted a review, later dismissed

2020-10-26 14:21 UTC, aleksandra-midor approved these changes

2020-10-26 14:33 UTC, kosmolet approved these changes

2020-10-26 14:39 UTC, merged