WIP: #2 As a receiver, I should be redirected to another page of questions when I click "No"
slosa-smartare/frontend pull request #8
Opened 2020-10-01 08:50 UTC by meerajm

2020-10-01 08:51 UTC, meerajm commented
![](https://github.trello.services/images/mini-trello-icon.png) [#2 As a receiver, I should be redirected to another page of questions when I click "No"](https://trello.com/c/UWYs7ob7/72-2-as-a-receiver-i-should-be-redirected-to-another-page-of-questions-when-i-click-no)

2020-10-01 08:51 UTC, miclovich requested changes

2020-10-01 08:51 UTC, miclovich commented on src/App.js
> +import Receiver from "./receiver-n-q2";
Terrible name for a file.

2020-10-08 09:21 UTC, meerajm commented
Closing this as a new PR was created for the same task.

2020-10-08 09:21 UTC, closed without merging